#!/bin/bash

PASS="$(shuf -i 100000000-999999999 -n 1)"
echo ${PASS}
#MD5="$(echo -n "${PASS}" | md5sum >> md5keys.txt)"
md5="${PASS}"
hash="$(echo -n "$md5" | md5sum )"
echo "$hash">> md5keys.txt
echo "$hash"

# crack with
# hashcat -m 0 -a 3  md5keys.txt ?d?d?d?d?d?d?d?d



#KEYS="$(md5sum plainkeys.txt >> md5keys.txt)"


